#ifndef KOSHMAR_STRINGIFY_H
#define KOSHMAR_STRINGIFY_H

#define KOSHMAR_STRINGIFY(x)           KOSHMAR_PRIMITIVE_STRINGIFY(x)
#define KOSHMAR_PRIMITIVE_STRINGIFY(x) #x

#endif // KOSHMAR_STRINGIFY_H
