# See <https://docs.readthedocs.io/en/stable/config-file/index.html>.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
