#include "test.h"

#include "../include/koshmar_pp/bool.h"

TEST(KOSHMAR_PP_NOT(0) == 1);
TEST(KOSHMAR_PP_NOT(1) == 0);

TEST(KOSHMAR_PP_AND(0, 0) == 0);
TEST(KOSHMAR_PP_AND(0, 1) == 0);
TEST(KOSHMAR_PP_AND(1, 0) == 0);
TEST(KOSHMAR_PP_AND(1, 1) == 1);

TEST(KOSHMAR_PP_OR(0, 0) == 0);
TEST(KOSHMAR_PP_OR(0, 1) == 1);
TEST(KOSHMAR_PP_OR(1, 0) == 1);
TEST(KOSHMAR_PP_OR(1, 1) == 1);

TEST(KOSHMAR_PP_XOR(0, 0) == 0);
TEST(KOSHMAR_PP_XOR(0, 1) == 1);
TEST(KOSHMAR_PP_XOR(1, 0) == 1);
TEST(KOSHMAR_PP_XOR(1, 1) == 0);
