#include <macrolop/assert.h>
#include <macrolop/lang.h>
#include <macrolop/logical.h>

MACROLOP_ASSERT_EQ(MACROLOP_NOT(v(0)), v(1));
MACROLOP_ASSERT_EQ(MACROLOP_NOT(v(1)), v(0));

MACROLOP_ASSERT_EQ(MACROLOP_AND(v(0), v(0)), v(0));
MACROLOP_ASSERT_EQ(MACROLOP_AND(v(0), v(1)), v(0));
MACROLOP_ASSERT_EQ(MACROLOP_AND(v(1), v(0)), v(0));
MACROLOP_ASSERT_EQ(MACROLOP_AND(v(1), v(1)), v(1));

MACROLOP_ASSERT_EQ(MACROLOP_OR(v(0), v(0)), v(0));
MACROLOP_ASSERT_EQ(MACROLOP_OR(v(0), v(1)), v(1));
MACROLOP_ASSERT_EQ(MACROLOP_OR(v(1), v(0)), v(1));
MACROLOP_ASSERT_EQ(MACROLOP_OR(v(1), v(1)), v(1));

MACROLOP_ASSERT_EQ(MACROLOP_XOR(v(0), v(0)), v(0));
MACROLOP_ASSERT_EQ(MACROLOP_XOR(v(0), v(1)), v(1));
MACROLOP_ASSERT_EQ(MACROLOP_XOR(v(1), v(0)), v(1));
MACROLOP_ASSERT_EQ(MACROLOP_XOR(v(1), v(1)), v(0));
