#include <epilepsy/assert.h>
#include <epilepsy/logical.h>

EPILEPSY_ASSERT_EQ(EPILEPSY_NOT(v(0)), v(1));
EPILEPSY_ASSERT_EQ(EPILEPSY_NOT(v(1)), v(0));

EPILEPSY_ASSERT_EQ(EPILEPSY_AND(v(0), v(0)), v(0));
EPILEPSY_ASSERT_EQ(EPILEPSY_AND(v(0), v(1)), v(0));
EPILEPSY_ASSERT_EQ(EPILEPSY_AND(v(1), v(0)), v(0));
EPILEPSY_ASSERT_EQ(EPILEPSY_AND(v(1), v(1)), v(1));

EPILEPSY_ASSERT_EQ(EPILEPSY_OR(v(0), v(0)), v(0));
EPILEPSY_ASSERT_EQ(EPILEPSY_OR(v(0), v(1)), v(1));
EPILEPSY_ASSERT_EQ(EPILEPSY_OR(v(1), v(0)), v(1));
EPILEPSY_ASSERT_EQ(EPILEPSY_OR(v(1), v(1)), v(1));

EPILEPSY_ASSERT_EQ(EPILEPSY_XOR(v(0), v(0)), v(0));
EPILEPSY_ASSERT_EQ(EPILEPSY_XOR(v(0), v(1)), v(1));
EPILEPSY_ASSERT_EQ(EPILEPSY_XOR(v(1), v(0)), v(1));
EPILEPSY_ASSERT_EQ(EPILEPSY_XOR(v(1), v(1)), v(0));
