#include <epilepsy/assert.h>
#include <epilepsy/lang.h>
#include <epilepsy/uint.h>

// EPILEPSY_UIntInc

EPILEPSY_ASSERT_EQ(EPILEPSY_UIntInc(v(0)), v(1));
EPILEPSY_ASSERT_EQ(EPILEPSY_UIntInc(v(15)), v(16));
EPILEPSY_ASSERT_EQ(EPILEPSY_UIntInc(v(198)), v(199));
EPILEPSY_ASSERT_EQ(EPILEPSY_UIntInc(v(1022)), v(1023));

// EPILEPSY_UIntDec

EPILEPSY_ASSERT_EQ(EPILEPSY_UIntDec(v(1)), v(0));
EPILEPSY_ASSERT_EQ(EPILEPSY_UIntDec(v(71)), v(70));
EPILEPSY_ASSERT_EQ(EPILEPSY_UIntDec(v(918)), v(917));
EPILEPSY_ASSERT_EQ(EPILEPSY_UIntDec(v(1023)), v(1022));

// EPILEPSY_UIntEq

EPILEPSY_ASSERT(EPILEPSY_UIntEq(v(0), v(0)));
EPILEPSY_ASSERT(EPILEPSY_UIntEq(v(18), v(18)));
EPILEPSY_ASSERT(EPILEPSY_UIntEq(v(910), v(910)));
EPILEPSY_ASSERT(EPILEPSY_UIntEq(v(1023), v(1023)));

// EPILEPSY_UIntNeq

EPILEPSY_ASSERT(EPILEPSY_UIntNeq(v(0), v(1)));
EPILEPSY_ASSERT(EPILEPSY_UIntNeq(v(0), v(1023)));
EPILEPSY_ASSERT(EPILEPSY_UIntNeq(v(1), v(34)));
EPILEPSY_ASSERT(EPILEPSY_UIntNeq(v(184), v(1019)));
EPILEPSY_ASSERT(EPILEPSY_UIntNeq(v(603), v(16)));

// EPILEPSY_UIntGreater

EPILEPSY_ASSERT(EPILEPSY_UIntGreater(v(1), v(0)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreater(v(1023), v(0)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreater(v(5), v(4)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreater(v(147), v(80)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreater(v(619), v(401)));

// EPILEPSY_UIntLesser

EPILEPSY_ASSERT(EPILEPSY_UIntLesser(v(0), v(1)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesser(v(0), v(1023)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesser(v(19), v(25)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesser(v(109), v(110)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesser(v(817), v(1003)));

// EPILEPSY_UIntGreaterEq

EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(0), v(0)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(18), v(18)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(175), v(175)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(1023), v(1023)));

EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(1), v(0)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(1023), v(0)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(19), v(10)));
EPILEPSY_ASSERT(EPILEPSY_UIntGreaterEq(v(760), v(508)));

// EPILEPSY_UIntLesserEq

EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(0), v(0)));

EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(2), v(2)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(1), v(1)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(25), v(25)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(498), v(498)));

EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(0), v(1)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(0), v(1023)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(18), v(27)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(82), v(90)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(345), v(346)));
EPILEPSY_ASSERT(EPILEPSY_UIntLesserEq(v(901), v(1023)));
