#include "test.h"

#include "../include/agony_pp/eval.h"
#include "../include/agony_pp/lang.h"

#include "../include/agony_pp/uint.h"

// AGONY_PP_UINT_INC

TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_INC, v(0))) == 1);
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_INC, v(15))) == 16);
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_INC, v(198))) == 199);
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_INC, v(1022))) == 1023);

// AGONY_PP_UINT_DEC

TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_DEC, v(1))) == 0);
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_DEC, v(71))) == 70);
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_DEC, v(918))) == 917);
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_DEC, v(1023))) == 1022);

// AGONY_PP_UINT_EQ

TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_EQ, v(0) v(0))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_EQ, v(18) v(18))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_EQ, v(910) v(910))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_EQ, v(1023) v(1023))));

// AGONY_PP_UINT_NEQ

TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_NEQ, v(0) v(1))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_NEQ, v(1) v(34))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_NEQ, v(184) v(1019))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_NEQ, v(603) v(16))));

// AGONY_PP_UINT_GREATER

/*
TEST(!AGONY_PP_UINT_GREATER(0, 0));
TEST(!AGONY_PP_UINT_GREATER(0, 839));

TEST(!AGONY_PP_UINT_GREATER(19, 19));
TEST(!AGONY_PP_UINT_GREATER(933, 933));
TEST(!AGONY_PP_UINT_GREATER(148, 148));
TEST(!AGONY_PP_UINT_GREATER(793, 793));

TEST(AGONY_PP_UINT_GREATER(5, 4));
TEST(AGONY_PP_UINT_GREATER(1, 0));
TEST(AGONY_PP_UINT_GREATER(147, 80));
TEST(AGONY_PP_UINT_GREATER(619, 401));
*/

// AGONY_PP_UINT_LESSER
== == == == == == TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_LESSER, v(0) v(1))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_LESSER, v(19) v(25))));
TEST(AGONY_PP_EVAL(c(AGONY_PP_UINT_LESSER, v(817) v(1003))));

// AGONY_PP_UINT_GREATER_EQUAL

/*
TEST(AGONY_PP_UINT_GREATER_EQUAL(0, 0));
TEST(!AGONY_PP_UINT_GREATER_EQUAL(0, 15));

TEST(AGONY_PP_UINT_GREATER_EQUAL(18, 18));
TEST(AGONY_PP_UINT_GREATER_EQUAL(191, 191));
TEST(AGONY_PP_UINT_GREATER_EQUAL(175, 175));
TEST(AGONY_PP_UINT_GREATER_EQUAL(867, 867));

TEST(AGONY_PP_UINT_GREATER_EQUAL(187, 19));
TEST(AGONY_PP_UINT_GREATER_EQUAL(19, 10));
TEST(AGONY_PP_UINT_GREATER_EQUAL(199, 198));
TEST(AGONY_PP_UINT_GREATER_EQUAL(760, 508));

// AGONY_PP_UINT_LESSER_EQUAL

TEST(AGONY_PP_UINT_LESSER_EQUAL(0, 0));
TEST(!AGONY_PP_UINT_LESSER_EQUAL(180, 18));

TEST(AGONY_PP_UINT_LESSER_EQUAL(2, 2));
TEST(AGONY_PP_UINT_LESSER_EQUAL(1, 1));
TEST(AGONY_PP_UINT_LESSER_EQUAL(25, 25));
TEST(AGONY_PP_UINT_LESSER_EQUAL(498, 498));

TEST(AGONY_PP_UINT_LESSER_EQUAL(18, 27));
TEST(AGONY_PP_UINT_LESSER_EQUAL(82, 90));
TEST(AGONY_PP_UINT_LESSER_EQUAL(345, 346));
TEST(AGONY_PP_UINT_LESSER_EQUAL(901, 1008));
*/
