#ifndef EPILEPSY_UINT_DIV_H
#define EPILEPSY_UINT_DIV_H

#include <epilepsy/lang.h>
#include <epilepsy/maybe.h>
#include <epilepsy/priv/aux.h>
#include <epilepsy/priv/variadics/get.h>

#define EPILEPSY_uintDiv_IMPL(x, y)                                                                \
    EPILEPSY_matchWithArgs(EPILEPSY_uintDivChecked(v(x), v(y)), v(EPILEPSY_PRIV_uintDiv_), v(x, y))
#define EPILEPSY_PRIV_uintDiv_nothing_IMPL(x, y)                                                   \
    EPILEPSY_fatal(EPILEPSY_uintDiv, `x` is not divisible by `y`)
#define EPILEPSY_PRIV_uintDiv_just_IMPL(n, _x, _y) v(n)

#define EPILEPSY_uintDivChecked_IMPL(x, y)                                                         \
    EPILEPSY_PRIV_UNPARENTHESISE(EPILEPSY_PRIV_VARIADICS_SND(                                      \
        EPILEPSY_PRIV_CAT_4(EPILEPSY_PRIV_UINT_DIV_, x, _, y)(),                                   \
        (EPILEPSY_nothing()),                                                                      \
        ~))

#define EPILEPSY_PRIV_UINT_DIV_0_1() ~, (EPILEPSY_just(v(0)))

#define EPILEPSY_PRIV_UINT_DIV_1_1() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_2_1() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_2_2() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_3_1() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_3_3() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_4_1() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_4_2() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_4_4() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_5_1() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_5_5() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_6_1() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_6_3() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_6_2() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_6_6() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_7_1() ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_7_7() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_8_1() ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_8_4() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_8_2() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_8_8() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_9_1() ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_9_3() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_9_9() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_10_1()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_10_5()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_10_2()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_10_10() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_11_1()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_11_11() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_12_1()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_12_6()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_12_4()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_12_3()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_12_2()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_12_12() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_13_1()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_13_13() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_14_1()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_14_7()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_14_2()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_14_14() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_15_1()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_15_5()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_15_3()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_15_15() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_16_1()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_16_8()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_16_4()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_16_2()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_16_16() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_17_1()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_17_17() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_18_1()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_18_9()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_18_6()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_18_3()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_18_2()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_18_18() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_19_1()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_19_19() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_20_1()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_20_10() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_20_5()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_20_4()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_20_2()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_20_20() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_21_1()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_21_7()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_21_3()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_21_21() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_22_1()  ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_22_11() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_22_2()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_22_22() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_23_1()  ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_23_23() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_24_1()  ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_24_12() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_24_8()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_24_6()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_24_4()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_24_3()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_24_2()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_24_24() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_25_1()  ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_25_5()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_25_25() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_26_1()  ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_26_13() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_26_2()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_26_26() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_27_1()  ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_27_9()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_27_3()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_27_27() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_28_1()  ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_28_14() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_28_7()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_28_4()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_28_2()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_28_28() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_29_1()  ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_29_29() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_30_1()  ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_30_15() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_30_10() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_30_6()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_30_5()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_30_3()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_30_2()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_30_30() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_31_1()  ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_31_31() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_32_1()  ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_32_16() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_32_8()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_32_4()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_32_2()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_32_32() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_33_1()  ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_33_11() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_33_3()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_33_33() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_34_1()  ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_34_17() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_34_2()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_34_34() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_35_1()  ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_35_7()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_35_5()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_35_35() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_36_1()  ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_36_18() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_36_12() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_36_9()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_36_6()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_36_4()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_36_3()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_36_2()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_36_36() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_37_1()  ~, (EPILEPSY_just(v(37)))
#define EPILEPSY_PRIV_UINT_DIV_37_37() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_38_1()  ~, (EPILEPSY_just(v(38)))
#define EPILEPSY_PRIV_UINT_DIV_38_19() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_38_2()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_38_38() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_39_1()  ~, (EPILEPSY_just(v(39)))
#define EPILEPSY_PRIV_UINT_DIV_39_13() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_39_3()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_39_39() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_40_1()  ~, (EPILEPSY_just(v(40)))
#define EPILEPSY_PRIV_UINT_DIV_40_20() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_40_10() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_40_8()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_40_5()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_40_4()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_40_2()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_40_40() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_41_1()  ~, (EPILEPSY_just(v(41)))
#define EPILEPSY_PRIV_UINT_DIV_41_41() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_42_1()  ~, (EPILEPSY_just(v(42)))
#define EPILEPSY_PRIV_UINT_DIV_42_21() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_42_14() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_42_7()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_42_6()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_42_3()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_42_2()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_42_42() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_43_1()  ~, (EPILEPSY_just(v(43)))
#define EPILEPSY_PRIV_UINT_DIV_43_43() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_44_1()  ~, (EPILEPSY_just(v(44)))
#define EPILEPSY_PRIV_UINT_DIV_44_22() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_44_11() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_44_4()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_44_2()  ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_44_44() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_45_1()  ~, (EPILEPSY_just(v(45)))
#define EPILEPSY_PRIV_UINT_DIV_45_15() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_45_9()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_45_5()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_45_3()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_45_45() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_46_1()  ~, (EPILEPSY_just(v(46)))
#define EPILEPSY_PRIV_UINT_DIV_46_23() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_46_2()  ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_46_46() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_47_1()  ~, (EPILEPSY_just(v(47)))
#define EPILEPSY_PRIV_UINT_DIV_47_47() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_48_1()  ~, (EPILEPSY_just(v(48)))
#define EPILEPSY_PRIV_UINT_DIV_48_24() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_48_16() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_48_12() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_48_8()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_48_6()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_48_4()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_48_3()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_48_2()  ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_48_48() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_49_1()  ~, (EPILEPSY_just(v(49)))
#define EPILEPSY_PRIV_UINT_DIV_49_7()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_49_49() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_50_1()  ~, (EPILEPSY_just(v(50)))
#define EPILEPSY_PRIV_UINT_DIV_50_25() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_50_10() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_50_5()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_50_2()  ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_50_50() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_51_1()  ~, (EPILEPSY_just(v(51)))
#define EPILEPSY_PRIV_UINT_DIV_51_17() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_51_3()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_51_51() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_52_1()  ~, (EPILEPSY_just(v(52)))
#define EPILEPSY_PRIV_UINT_DIV_52_26() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_52_13() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_52_4()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_52_2()  ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_52_52() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_53_1()  ~, (EPILEPSY_just(v(53)))
#define EPILEPSY_PRIV_UINT_DIV_53_53() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_54_1()  ~, (EPILEPSY_just(v(54)))
#define EPILEPSY_PRIV_UINT_DIV_54_27() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_54_18() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_54_9()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_54_6()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_54_3()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_54_2()  ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_54_54() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_55_1()  ~, (EPILEPSY_just(v(55)))
#define EPILEPSY_PRIV_UINT_DIV_55_11() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_55_5()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_55_55() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_56_1()  ~, (EPILEPSY_just(v(56)))
#define EPILEPSY_PRIV_UINT_DIV_56_28() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_56_14() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_56_8()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_56_7()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_56_4()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_56_2()  ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_56_56() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_57_1()  ~, (EPILEPSY_just(v(57)))
#define EPILEPSY_PRIV_UINT_DIV_57_19() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_57_3()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_57_57() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_58_1()  ~, (EPILEPSY_just(v(58)))
#define EPILEPSY_PRIV_UINT_DIV_58_29() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_58_2()  ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_58_58() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_59_1()  ~, (EPILEPSY_just(v(59)))
#define EPILEPSY_PRIV_UINT_DIV_59_59() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_60_1()  ~, (EPILEPSY_just(v(60)))
#define EPILEPSY_PRIV_UINT_DIV_60_30() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_60_20() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_60_15() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_60_12() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_60_10() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_60_6()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_60_5()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_60_4()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_60_3()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_60_2()  ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_60_60() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_61_1()  ~, (EPILEPSY_just(v(61)))
#define EPILEPSY_PRIV_UINT_DIV_61_61() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_62_1()  ~, (EPILEPSY_just(v(62)))
#define EPILEPSY_PRIV_UINT_DIV_62_31() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_62_2()  ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_62_62() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_63_1()  ~, (EPILEPSY_just(v(63)))
#define EPILEPSY_PRIV_UINT_DIV_63_21() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_63_9()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_63_7()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_63_3()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_63_63() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_64_1()  ~, (EPILEPSY_just(v(64)))
#define EPILEPSY_PRIV_UINT_DIV_64_32() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_64_16() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_64_8()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_64_4()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_64_2()  ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_64_64() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_65_1()  ~, (EPILEPSY_just(v(65)))
#define EPILEPSY_PRIV_UINT_DIV_65_13() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_65_5()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_65_65() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_66_1()  ~, (EPILEPSY_just(v(66)))
#define EPILEPSY_PRIV_UINT_DIV_66_33() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_66_22() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_66_11() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_66_6()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_66_3()  ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_66_2()  ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_66_66() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_67_1()  ~, (EPILEPSY_just(v(67)))
#define EPILEPSY_PRIV_UINT_DIV_67_67() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_68_1()  ~, (EPILEPSY_just(v(68)))
#define EPILEPSY_PRIV_UINT_DIV_68_34() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_68_17() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_68_4()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_68_2()  ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_68_68() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_69_1()  ~, (EPILEPSY_just(v(69)))
#define EPILEPSY_PRIV_UINT_DIV_69_23() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_69_3()  ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_69_69() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_70_1()  ~, (EPILEPSY_just(v(70)))
#define EPILEPSY_PRIV_UINT_DIV_70_35() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_70_14() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_70_10() ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_70_7()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_70_5()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_70_2()  ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_70_70() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_71_1()  ~, (EPILEPSY_just(v(71)))
#define EPILEPSY_PRIV_UINT_DIV_71_71() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_72_1()  ~, (EPILEPSY_just(v(72)))
#define EPILEPSY_PRIV_UINT_DIV_72_36() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_72_24() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_72_18() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_72_12() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_72_9()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_72_8()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_72_6()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_72_4()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_72_3()  ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_72_2()  ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_72_72() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_73_1()  ~, (EPILEPSY_just(v(73)))
#define EPILEPSY_PRIV_UINT_DIV_73_73() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_74_1()  ~, (EPILEPSY_just(v(74)))
#define EPILEPSY_PRIV_UINT_DIV_74_37() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_74_2()  ~, (EPILEPSY_just(v(37)))
#define EPILEPSY_PRIV_UINT_DIV_74_74() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_75_1()  ~, (EPILEPSY_just(v(75)))
#define EPILEPSY_PRIV_UINT_DIV_75_25() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_75_15() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_75_5()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_75_3()  ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_75_75() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_76_1()  ~, (EPILEPSY_just(v(76)))
#define EPILEPSY_PRIV_UINT_DIV_76_38() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_76_19() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_76_4()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_76_2()  ~, (EPILEPSY_just(v(38)))
#define EPILEPSY_PRIV_UINT_DIV_76_76() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_77_1()  ~, (EPILEPSY_just(v(77)))
#define EPILEPSY_PRIV_UINT_DIV_77_11() ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_77_7()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_77_77() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_78_1()  ~, (EPILEPSY_just(v(78)))
#define EPILEPSY_PRIV_UINT_DIV_78_39() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_78_26() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_78_13() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_78_6()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_78_3()  ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_78_2()  ~, (EPILEPSY_just(v(39)))
#define EPILEPSY_PRIV_UINT_DIV_78_78() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_79_1()  ~, (EPILEPSY_just(v(79)))
#define EPILEPSY_PRIV_UINT_DIV_79_79() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_80_1()  ~, (EPILEPSY_just(v(80)))
#define EPILEPSY_PRIV_UINT_DIV_80_40() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_80_20() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_80_16() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_80_10() ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_80_8()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_80_5()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_80_4()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_80_2()  ~, (EPILEPSY_just(v(40)))
#define EPILEPSY_PRIV_UINT_DIV_80_80() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_81_1()  ~, (EPILEPSY_just(v(81)))
#define EPILEPSY_PRIV_UINT_DIV_81_27() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_81_9()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_81_3()  ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_81_81() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_82_1()  ~, (EPILEPSY_just(v(82)))
#define EPILEPSY_PRIV_UINT_DIV_82_41() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_82_2()  ~, (EPILEPSY_just(v(41)))
#define EPILEPSY_PRIV_UINT_DIV_82_82() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_83_1()  ~, (EPILEPSY_just(v(83)))
#define EPILEPSY_PRIV_UINT_DIV_83_83() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_84_1()  ~, (EPILEPSY_just(v(84)))
#define EPILEPSY_PRIV_UINT_DIV_84_42() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_84_28() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_84_21() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_84_14() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_84_12() ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_84_7()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_84_6()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_84_4()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_84_3()  ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_84_2()  ~, (EPILEPSY_just(v(42)))
#define EPILEPSY_PRIV_UINT_DIV_84_84() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_85_1()  ~, (EPILEPSY_just(v(85)))
#define EPILEPSY_PRIV_UINT_DIV_85_17() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_85_5()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_85_85() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_86_1()  ~, (EPILEPSY_just(v(86)))
#define EPILEPSY_PRIV_UINT_DIV_86_43() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_86_2()  ~, (EPILEPSY_just(v(43)))
#define EPILEPSY_PRIV_UINT_DIV_86_86() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_87_1()  ~, (EPILEPSY_just(v(87)))
#define EPILEPSY_PRIV_UINT_DIV_87_29() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_87_3()  ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_87_87() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_88_1()  ~, (EPILEPSY_just(v(88)))
#define EPILEPSY_PRIV_UINT_DIV_88_44() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_88_22() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_88_11() ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_88_8()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_88_4()  ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_88_2()  ~, (EPILEPSY_just(v(44)))
#define EPILEPSY_PRIV_UINT_DIV_88_88() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_89_1()  ~, (EPILEPSY_just(v(89)))
#define EPILEPSY_PRIV_UINT_DIV_89_89() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_90_1()  ~, (EPILEPSY_just(v(90)))
#define EPILEPSY_PRIV_UINT_DIV_90_45() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_90_30() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_90_18() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_90_15() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_90_10() ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_90_9()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_90_6()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_90_5()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_90_3()  ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_90_2()  ~, (EPILEPSY_just(v(45)))
#define EPILEPSY_PRIV_UINT_DIV_90_90() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_91_1()  ~, (EPILEPSY_just(v(91)))
#define EPILEPSY_PRIV_UINT_DIV_91_13() ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_91_7()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_91_91() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_92_1()  ~, (EPILEPSY_just(v(92)))
#define EPILEPSY_PRIV_UINT_DIV_92_46() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_92_23() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_92_4()  ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_92_2()  ~, (EPILEPSY_just(v(46)))
#define EPILEPSY_PRIV_UINT_DIV_92_92() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_93_1()  ~, (EPILEPSY_just(v(93)))
#define EPILEPSY_PRIV_UINT_DIV_93_31() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_93_3()  ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_93_93() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_94_1()  ~, (EPILEPSY_just(v(94)))
#define EPILEPSY_PRIV_UINT_DIV_94_47() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_94_2()  ~, (EPILEPSY_just(v(47)))
#define EPILEPSY_PRIV_UINT_DIV_94_94() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_95_1()  ~, (EPILEPSY_just(v(95)))
#define EPILEPSY_PRIV_UINT_DIV_95_19() ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_95_5()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_95_95() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_96_1()  ~, (EPILEPSY_just(v(96)))
#define EPILEPSY_PRIV_UINT_DIV_96_48() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_96_32() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_96_24() ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_96_16() ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_96_12() ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_96_8()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_96_6()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_96_4()  ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_96_3()  ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_96_2()  ~, (EPILEPSY_just(v(48)))
#define EPILEPSY_PRIV_UINT_DIV_96_96() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_97_1()  ~, (EPILEPSY_just(v(97)))
#define EPILEPSY_PRIV_UINT_DIV_97_97() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_98_1()  ~, (EPILEPSY_just(v(98)))
#define EPILEPSY_PRIV_UINT_DIV_98_49() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_98_14() ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_98_7()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_98_2()  ~, (EPILEPSY_just(v(49)))
#define EPILEPSY_PRIV_UINT_DIV_98_98() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_99_1()  ~, (EPILEPSY_just(v(99)))
#define EPILEPSY_PRIV_UINT_DIV_99_33() ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_99_11() ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_99_9()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_99_3()  ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_99_99() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_100_1()   ~, (EPILEPSY_just(v(100)))
#define EPILEPSY_PRIV_UINT_DIV_100_50()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_100_25()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_100_20()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_100_10()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_100_5()   ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_100_4()   ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_100_2()   ~, (EPILEPSY_just(v(50)))
#define EPILEPSY_PRIV_UINT_DIV_100_100() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_101_1()   ~, (EPILEPSY_just(v(101)))
#define EPILEPSY_PRIV_UINT_DIV_101_101() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_102_1()   ~, (EPILEPSY_just(v(102)))
#define EPILEPSY_PRIV_UINT_DIV_102_51()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_102_34()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_102_17()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_102_6()   ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_102_3()   ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_102_2()   ~, (EPILEPSY_just(v(51)))
#define EPILEPSY_PRIV_UINT_DIV_102_102() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_103_1()   ~, (EPILEPSY_just(v(103)))
#define EPILEPSY_PRIV_UINT_DIV_103_103() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_104_1()   ~, (EPILEPSY_just(v(104)))
#define EPILEPSY_PRIV_UINT_DIV_104_52()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_104_26()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_104_13()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_104_8()   ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_104_4()   ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_104_2()   ~, (EPILEPSY_just(v(52)))
#define EPILEPSY_PRIV_UINT_DIV_104_104() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_105_1()   ~, (EPILEPSY_just(v(105)))
#define EPILEPSY_PRIV_UINT_DIV_105_35()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_105_21()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_105_15()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_105_7()   ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_105_5()   ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_105_3()   ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_105_105() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_106_1()   ~, (EPILEPSY_just(v(106)))
#define EPILEPSY_PRIV_UINT_DIV_106_53()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_106_2()   ~, (EPILEPSY_just(v(53)))
#define EPILEPSY_PRIV_UINT_DIV_106_106() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_107_1()   ~, (EPILEPSY_just(v(107)))
#define EPILEPSY_PRIV_UINT_DIV_107_107() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_108_1()   ~, (EPILEPSY_just(v(108)))
#define EPILEPSY_PRIV_UINT_DIV_108_54()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_108_36()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_108_27()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_108_18()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_108_12()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_108_9()   ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_108_6()   ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_108_4()   ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_108_3()   ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_108_2()   ~, (EPILEPSY_just(v(54)))
#define EPILEPSY_PRIV_UINT_DIV_108_108() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_109_1()   ~, (EPILEPSY_just(v(109)))
#define EPILEPSY_PRIV_UINT_DIV_109_109() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_110_1()   ~, (EPILEPSY_just(v(110)))
#define EPILEPSY_PRIV_UINT_DIV_110_55()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_110_22()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_110_11()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_110_10()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_110_5()   ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_110_2()   ~, (EPILEPSY_just(v(55)))
#define EPILEPSY_PRIV_UINT_DIV_110_110() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_111_1()   ~, (EPILEPSY_just(v(111)))
#define EPILEPSY_PRIV_UINT_DIV_111_37()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_111_3()   ~, (EPILEPSY_just(v(37)))
#define EPILEPSY_PRIV_UINT_DIV_111_111() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_112_1()   ~, (EPILEPSY_just(v(112)))
#define EPILEPSY_PRIV_UINT_DIV_112_56()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_112_28()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_112_16()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_112_14()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_112_8()   ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_112_7()   ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_112_4()   ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_112_2()   ~, (EPILEPSY_just(v(56)))
#define EPILEPSY_PRIV_UINT_DIV_112_112() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_113_1()   ~, (EPILEPSY_just(v(113)))
#define EPILEPSY_PRIV_UINT_DIV_113_113() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_114_1()   ~, (EPILEPSY_just(v(114)))
#define EPILEPSY_PRIV_UINT_DIV_114_57()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_114_38()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_114_19()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_114_6()   ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_114_3()   ~, (EPILEPSY_just(v(38)))
#define EPILEPSY_PRIV_UINT_DIV_114_2()   ~, (EPILEPSY_just(v(57)))
#define EPILEPSY_PRIV_UINT_DIV_114_114() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_115_1()   ~, (EPILEPSY_just(v(115)))
#define EPILEPSY_PRIV_UINT_DIV_115_23()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_115_5()   ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_115_115() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_116_1()   ~, (EPILEPSY_just(v(116)))
#define EPILEPSY_PRIV_UINT_DIV_116_58()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_116_29()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_116_4()   ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_116_2()   ~, (EPILEPSY_just(v(58)))
#define EPILEPSY_PRIV_UINT_DIV_116_116() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_117_1()   ~, (EPILEPSY_just(v(117)))
#define EPILEPSY_PRIV_UINT_DIV_117_39()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_117_13()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_117_9()   ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_117_3()   ~, (EPILEPSY_just(v(39)))
#define EPILEPSY_PRIV_UINT_DIV_117_117() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_118_1()   ~, (EPILEPSY_just(v(118)))
#define EPILEPSY_PRIV_UINT_DIV_118_59()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_118_2()   ~, (EPILEPSY_just(v(59)))
#define EPILEPSY_PRIV_UINT_DIV_118_118() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_119_1()   ~, (EPILEPSY_just(v(119)))
#define EPILEPSY_PRIV_UINT_DIV_119_17()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_119_7()   ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_119_119() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_120_1()   ~, (EPILEPSY_just(v(120)))
#define EPILEPSY_PRIV_UINT_DIV_120_60()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_120_40()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_120_30()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_120_24()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_120_20()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_120_15()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_120_12()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_120_10()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_120_8()   ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_120_6()   ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_120_5()   ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_120_4()   ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_120_3()   ~, (EPILEPSY_just(v(40)))
#define EPILEPSY_PRIV_UINT_DIV_120_2()   ~, (EPILEPSY_just(v(60)))
#define EPILEPSY_PRIV_UINT_DIV_120_120() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_121_1()   ~, (EPILEPSY_just(v(121)))
#define EPILEPSY_PRIV_UINT_DIV_121_11()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_121_121() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_122_1()   ~, (EPILEPSY_just(v(122)))
#define EPILEPSY_PRIV_UINT_DIV_122_61()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_122_2()   ~, (EPILEPSY_just(v(61)))
#define EPILEPSY_PRIV_UINT_DIV_122_122() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_123_1()   ~, (EPILEPSY_just(v(123)))
#define EPILEPSY_PRIV_UINT_DIV_123_41()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_123_3()   ~, (EPILEPSY_just(v(41)))
#define EPILEPSY_PRIV_UINT_DIV_123_123() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_124_1()   ~, (EPILEPSY_just(v(124)))
#define EPILEPSY_PRIV_UINT_DIV_124_62()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_124_31()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_124_4()   ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_124_2()   ~, (EPILEPSY_just(v(62)))
#define EPILEPSY_PRIV_UINT_DIV_124_124() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_125_1()   ~, (EPILEPSY_just(v(125)))
#define EPILEPSY_PRIV_UINT_DIV_125_25()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_125_5()   ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_125_125() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_126_1()   ~, (EPILEPSY_just(v(126)))
#define EPILEPSY_PRIV_UINT_DIV_126_63()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_126_42()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_126_21()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_126_18()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_126_14()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_126_9()   ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_126_7()   ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_126_6()   ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_126_3()   ~, (EPILEPSY_just(v(42)))
#define EPILEPSY_PRIV_UINT_DIV_126_2()   ~, (EPILEPSY_just(v(63)))
#define EPILEPSY_PRIV_UINT_DIV_126_126() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_127_1()   ~, (EPILEPSY_just(v(127)))
#define EPILEPSY_PRIV_UINT_DIV_127_127() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_128_1()   ~, (EPILEPSY_just(v(128)))
#define EPILEPSY_PRIV_UINT_DIV_128_64()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_128_32()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_128_16()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_128_8()   ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_128_4()   ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_128_2()   ~, (EPILEPSY_just(v(64)))
#define EPILEPSY_PRIV_UINT_DIV_128_128() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_129_1()   ~, (EPILEPSY_just(v(129)))
#define EPILEPSY_PRIV_UINT_DIV_129_43()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_129_3()   ~, (EPILEPSY_just(v(43)))
#define EPILEPSY_PRIV_UINT_DIV_129_129() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_130_1()   ~, (EPILEPSY_just(v(130)))
#define EPILEPSY_PRIV_UINT_DIV_130_65()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_130_26()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_130_13()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_130_10()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_130_5()   ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_130_2()   ~, (EPILEPSY_just(v(65)))
#define EPILEPSY_PRIV_UINT_DIV_130_130() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_131_1()   ~, (EPILEPSY_just(v(131)))
#define EPILEPSY_PRIV_UINT_DIV_131_131() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_132_1()   ~, (EPILEPSY_just(v(132)))
#define EPILEPSY_PRIV_UINT_DIV_132_66()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_132_44()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_132_33()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_132_22()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_132_12()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_132_11()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_132_6()   ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_132_4()   ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_132_3()   ~, (EPILEPSY_just(v(44)))
#define EPILEPSY_PRIV_UINT_DIV_132_2()   ~, (EPILEPSY_just(v(66)))
#define EPILEPSY_PRIV_UINT_DIV_132_132() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_133_1()   ~, (EPILEPSY_just(v(133)))
#define EPILEPSY_PRIV_UINT_DIV_133_19()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_133_7()   ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_133_133() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_134_1()   ~, (EPILEPSY_just(v(134)))
#define EPILEPSY_PRIV_UINT_DIV_134_67()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_134_2()   ~, (EPILEPSY_just(v(67)))
#define EPILEPSY_PRIV_UINT_DIV_134_134() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_135_1()   ~, (EPILEPSY_just(v(135)))
#define EPILEPSY_PRIV_UINT_DIV_135_45()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_135_27()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_135_15()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_135_9()   ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_135_5()   ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_135_3()   ~, (EPILEPSY_just(v(45)))
#define EPILEPSY_PRIV_UINT_DIV_135_135() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_136_1()   ~, (EPILEPSY_just(v(136)))
#define EPILEPSY_PRIV_UINT_DIV_136_68()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_136_34()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_136_17()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_136_8()   ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_136_4()   ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_136_2()   ~, (EPILEPSY_just(v(68)))
#define EPILEPSY_PRIV_UINT_DIV_136_136() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_137_1()   ~, (EPILEPSY_just(v(137)))
#define EPILEPSY_PRIV_UINT_DIV_137_137() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_138_1()   ~, (EPILEPSY_just(v(138)))
#define EPILEPSY_PRIV_UINT_DIV_138_69()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_138_46()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_138_23()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_138_6()   ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_138_3()   ~, (EPILEPSY_just(v(46)))
#define EPILEPSY_PRIV_UINT_DIV_138_2()   ~, (EPILEPSY_just(v(69)))
#define EPILEPSY_PRIV_UINT_DIV_138_138() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_139_1()   ~, (EPILEPSY_just(v(139)))
#define EPILEPSY_PRIV_UINT_DIV_139_139() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_140_1()   ~, (EPILEPSY_just(v(140)))
#define EPILEPSY_PRIV_UINT_DIV_140_70()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_140_35()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_140_28()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_140_20()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_140_14()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_140_10()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_140_7()   ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_140_5()   ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_140_4()   ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_140_2()   ~, (EPILEPSY_just(v(70)))
#define EPILEPSY_PRIV_UINT_DIV_140_140() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_141_1()   ~, (EPILEPSY_just(v(141)))
#define EPILEPSY_PRIV_UINT_DIV_141_47()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_141_3()   ~, (EPILEPSY_just(v(47)))
#define EPILEPSY_PRIV_UINT_DIV_141_141() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_142_1()   ~, (EPILEPSY_just(v(142)))
#define EPILEPSY_PRIV_UINT_DIV_142_71()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_142_2()   ~, (EPILEPSY_just(v(71)))
#define EPILEPSY_PRIV_UINT_DIV_142_142() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_143_1()   ~, (EPILEPSY_just(v(143)))
#define EPILEPSY_PRIV_UINT_DIV_143_13()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_143_11()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_143_143() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_144_1()   ~, (EPILEPSY_just(v(144)))
#define EPILEPSY_PRIV_UINT_DIV_144_72()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_144_48()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_144_36()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_144_24()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_144_18()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_144_16()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_144_12()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_144_9()   ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_144_8()   ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_144_6()   ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_144_4()   ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_144_3()   ~, (EPILEPSY_just(v(48)))
#define EPILEPSY_PRIV_UINT_DIV_144_2()   ~, (EPILEPSY_just(v(72)))
#define EPILEPSY_PRIV_UINT_DIV_144_144() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_145_1()   ~, (EPILEPSY_just(v(145)))
#define EPILEPSY_PRIV_UINT_DIV_145_29()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_145_5()   ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_145_145() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_146_1()   ~, (EPILEPSY_just(v(146)))
#define EPILEPSY_PRIV_UINT_DIV_146_73()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_146_2()   ~, (EPILEPSY_just(v(73)))
#define EPILEPSY_PRIV_UINT_DIV_146_146() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_147_1()   ~, (EPILEPSY_just(v(147)))
#define EPILEPSY_PRIV_UINT_DIV_147_49()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_147_21()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_147_7()   ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_147_3()   ~, (EPILEPSY_just(v(49)))
#define EPILEPSY_PRIV_UINT_DIV_147_147() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_148_1()   ~, (EPILEPSY_just(v(148)))
#define EPILEPSY_PRIV_UINT_DIV_148_74()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_148_37()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_148_4()   ~, (EPILEPSY_just(v(37)))
#define EPILEPSY_PRIV_UINT_DIV_148_2()   ~, (EPILEPSY_just(v(74)))
#define EPILEPSY_PRIV_UINT_DIV_148_148() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_149_1()   ~, (EPILEPSY_just(v(149)))
#define EPILEPSY_PRIV_UINT_DIV_149_149() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_150_1()   ~, (EPILEPSY_just(v(150)))
#define EPILEPSY_PRIV_UINT_DIV_150_75()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_150_50()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_150_30()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_150_25()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_150_15()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_150_10()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_150_6()   ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_150_5()   ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_150_3()   ~, (EPILEPSY_just(v(50)))
#define EPILEPSY_PRIV_UINT_DIV_150_2()   ~, (EPILEPSY_just(v(75)))
#define EPILEPSY_PRIV_UINT_DIV_150_150() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_151_1()   ~, (EPILEPSY_just(v(151)))
#define EPILEPSY_PRIV_UINT_DIV_151_151() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_152_1()   ~, (EPILEPSY_just(v(152)))
#define EPILEPSY_PRIV_UINT_DIV_152_76()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_152_38()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_152_19()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_152_8()   ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_152_4()   ~, (EPILEPSY_just(v(38)))
#define EPILEPSY_PRIV_UINT_DIV_152_2()   ~, (EPILEPSY_just(v(76)))
#define EPILEPSY_PRIV_UINT_DIV_152_152() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_153_1()   ~, (EPILEPSY_just(v(153)))
#define EPILEPSY_PRIV_UINT_DIV_153_51()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_153_17()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_153_9()   ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_153_3()   ~, (EPILEPSY_just(v(51)))
#define EPILEPSY_PRIV_UINT_DIV_153_153() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_154_1()   ~, (EPILEPSY_just(v(154)))
#define EPILEPSY_PRIV_UINT_DIV_154_77()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_154_22()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_154_14()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_154_11()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_154_7()   ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_154_2()   ~, (EPILEPSY_just(v(77)))
#define EPILEPSY_PRIV_UINT_DIV_154_154() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_155_1()   ~, (EPILEPSY_just(v(155)))
#define EPILEPSY_PRIV_UINT_DIV_155_31()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_155_5()   ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_155_155() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_156_1()   ~, (EPILEPSY_just(v(156)))
#define EPILEPSY_PRIV_UINT_DIV_156_78()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_156_52()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_156_39()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_156_26()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_156_13()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_156_12()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_156_6()   ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_156_4()   ~, (EPILEPSY_just(v(39)))
#define EPILEPSY_PRIV_UINT_DIV_156_3()   ~, (EPILEPSY_just(v(52)))
#define EPILEPSY_PRIV_UINT_DIV_156_2()   ~, (EPILEPSY_just(v(78)))
#define EPILEPSY_PRIV_UINT_DIV_156_156() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_157_1()   ~, (EPILEPSY_just(v(157)))
#define EPILEPSY_PRIV_UINT_DIV_157_157() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_158_1()   ~, (EPILEPSY_just(v(158)))
#define EPILEPSY_PRIV_UINT_DIV_158_79()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_158_2()   ~, (EPILEPSY_just(v(79)))
#define EPILEPSY_PRIV_UINT_DIV_158_158() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_159_1()   ~, (EPILEPSY_just(v(159)))
#define EPILEPSY_PRIV_UINT_DIV_159_53()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_159_3()   ~, (EPILEPSY_just(v(53)))
#define EPILEPSY_PRIV_UINT_DIV_159_159() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_160_1()   ~, (EPILEPSY_just(v(160)))
#define EPILEPSY_PRIV_UINT_DIV_160_80()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_160_40()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_160_32()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_160_20()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_160_16()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_160_10()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_160_8()   ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_160_5()   ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_160_4()   ~, (EPILEPSY_just(v(40)))
#define EPILEPSY_PRIV_UINT_DIV_160_2()   ~, (EPILEPSY_just(v(80)))
#define EPILEPSY_PRIV_UINT_DIV_160_160() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_161_1()   ~, (EPILEPSY_just(v(161)))
#define EPILEPSY_PRIV_UINT_DIV_161_23()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_161_7()   ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_161_161() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_162_1()   ~, (EPILEPSY_just(v(162)))
#define EPILEPSY_PRIV_UINT_DIV_162_81()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_162_54()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_162_27()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_162_18()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_162_9()   ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_162_6()   ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_162_3()   ~, (EPILEPSY_just(v(54)))
#define EPILEPSY_PRIV_UINT_DIV_162_2()   ~, (EPILEPSY_just(v(81)))
#define EPILEPSY_PRIV_UINT_DIV_162_162() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_163_1()   ~, (EPILEPSY_just(v(163)))
#define EPILEPSY_PRIV_UINT_DIV_163_163() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_164_1()   ~, (EPILEPSY_just(v(164)))
#define EPILEPSY_PRIV_UINT_DIV_164_82()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_164_41()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_164_4()   ~, (EPILEPSY_just(v(41)))
#define EPILEPSY_PRIV_UINT_DIV_164_2()   ~, (EPILEPSY_just(v(82)))
#define EPILEPSY_PRIV_UINT_DIV_164_164() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_165_1()   ~, (EPILEPSY_just(v(165)))
#define EPILEPSY_PRIV_UINT_DIV_165_55()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_165_33()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_165_15()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_165_11()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_165_5()   ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_165_3()   ~, (EPILEPSY_just(v(55)))
#define EPILEPSY_PRIV_UINT_DIV_165_165() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_166_1()   ~, (EPILEPSY_just(v(166)))
#define EPILEPSY_PRIV_UINT_DIV_166_83()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_166_2()   ~, (EPILEPSY_just(v(83)))
#define EPILEPSY_PRIV_UINT_DIV_166_166() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_167_1()   ~, (EPILEPSY_just(v(167)))
#define EPILEPSY_PRIV_UINT_DIV_167_167() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_168_1()   ~, (EPILEPSY_just(v(168)))
#define EPILEPSY_PRIV_UINT_DIV_168_84()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_168_56()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_168_42()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_168_28()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_168_24()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_168_21()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_168_14()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_168_12()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_168_8()   ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_168_7()   ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_168_6()   ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_168_4()   ~, (EPILEPSY_just(v(42)))
#define EPILEPSY_PRIV_UINT_DIV_168_3()   ~, (EPILEPSY_just(v(56)))
#define EPILEPSY_PRIV_UINT_DIV_168_2()   ~, (EPILEPSY_just(v(84)))
#define EPILEPSY_PRIV_UINT_DIV_168_168() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_169_1()   ~, (EPILEPSY_just(v(169)))
#define EPILEPSY_PRIV_UINT_DIV_169_13()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_169_169() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_170_1()   ~, (EPILEPSY_just(v(170)))
#define EPILEPSY_PRIV_UINT_DIV_170_85()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_170_34()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_170_17()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_170_10()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_170_5()   ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_170_2()   ~, (EPILEPSY_just(v(85)))
#define EPILEPSY_PRIV_UINT_DIV_170_170() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_171_1()   ~, (EPILEPSY_just(v(171)))
#define EPILEPSY_PRIV_UINT_DIV_171_57()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_171_19()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_171_9()   ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_171_3()   ~, (EPILEPSY_just(v(57)))
#define EPILEPSY_PRIV_UINT_DIV_171_171() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_172_1()   ~, (EPILEPSY_just(v(172)))
#define EPILEPSY_PRIV_UINT_DIV_172_86()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_172_43()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_172_4()   ~, (EPILEPSY_just(v(43)))
#define EPILEPSY_PRIV_UINT_DIV_172_2()   ~, (EPILEPSY_just(v(86)))
#define EPILEPSY_PRIV_UINT_DIV_172_172() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_173_1()   ~, (EPILEPSY_just(v(173)))
#define EPILEPSY_PRIV_UINT_DIV_173_173() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_174_1()   ~, (EPILEPSY_just(v(174)))
#define EPILEPSY_PRIV_UINT_DIV_174_87()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_174_58()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_174_29()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_174_6()   ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_174_3()   ~, (EPILEPSY_just(v(58)))
#define EPILEPSY_PRIV_UINT_DIV_174_2()   ~, (EPILEPSY_just(v(87)))
#define EPILEPSY_PRIV_UINT_DIV_174_174() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_175_1()   ~, (EPILEPSY_just(v(175)))
#define EPILEPSY_PRIV_UINT_DIV_175_35()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_175_25()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_175_7()   ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_175_5()   ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_175_175() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_176_1()   ~, (EPILEPSY_just(v(176)))
#define EPILEPSY_PRIV_UINT_DIV_176_88()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_176_44()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_176_22()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_176_16()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_176_11()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_176_8()   ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_176_4()   ~, (EPILEPSY_just(v(44)))
#define EPILEPSY_PRIV_UINT_DIV_176_2()   ~, (EPILEPSY_just(v(88)))
#define EPILEPSY_PRIV_UINT_DIV_176_176() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_177_1()   ~, (EPILEPSY_just(v(177)))
#define EPILEPSY_PRIV_UINT_DIV_177_59()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_177_3()   ~, (EPILEPSY_just(v(59)))
#define EPILEPSY_PRIV_UINT_DIV_177_177() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_178_1()   ~, (EPILEPSY_just(v(178)))
#define EPILEPSY_PRIV_UINT_DIV_178_89()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_178_2()   ~, (EPILEPSY_just(v(89)))
#define EPILEPSY_PRIV_UINT_DIV_178_178() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_179_1()   ~, (EPILEPSY_just(v(179)))
#define EPILEPSY_PRIV_UINT_DIV_179_179() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_180_1()   ~, (EPILEPSY_just(v(180)))
#define EPILEPSY_PRIV_UINT_DIV_180_90()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_180_60()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_180_45()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_180_36()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_180_30()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_180_20()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_180_18()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_180_15()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_180_12()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_180_10()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_180_9()   ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_180_6()   ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_180_5()   ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_180_4()   ~, (EPILEPSY_just(v(45)))
#define EPILEPSY_PRIV_UINT_DIV_180_3()   ~, (EPILEPSY_just(v(60)))
#define EPILEPSY_PRIV_UINT_DIV_180_2()   ~, (EPILEPSY_just(v(90)))
#define EPILEPSY_PRIV_UINT_DIV_180_180() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_181_1()   ~, (EPILEPSY_just(v(181)))
#define EPILEPSY_PRIV_UINT_DIV_181_181() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_182_1()   ~, (EPILEPSY_just(v(182)))
#define EPILEPSY_PRIV_UINT_DIV_182_91()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_182_26()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_182_14()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_182_13()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_182_7()   ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_182_2()   ~, (EPILEPSY_just(v(91)))
#define EPILEPSY_PRIV_UINT_DIV_182_182() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_183_1()   ~, (EPILEPSY_just(v(183)))
#define EPILEPSY_PRIV_UINT_DIV_183_61()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_183_3()   ~, (EPILEPSY_just(v(61)))
#define EPILEPSY_PRIV_UINT_DIV_183_183() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_184_1()   ~, (EPILEPSY_just(v(184)))
#define EPILEPSY_PRIV_UINT_DIV_184_92()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_184_46()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_184_23()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_184_8()   ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_184_4()   ~, (EPILEPSY_just(v(46)))
#define EPILEPSY_PRIV_UINT_DIV_184_2()   ~, (EPILEPSY_just(v(92)))
#define EPILEPSY_PRIV_UINT_DIV_184_184() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_185_1()   ~, (EPILEPSY_just(v(185)))
#define EPILEPSY_PRIV_UINT_DIV_185_37()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_185_5()   ~, (EPILEPSY_just(v(37)))
#define EPILEPSY_PRIV_UINT_DIV_185_185() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_186_1()   ~, (EPILEPSY_just(v(186)))
#define EPILEPSY_PRIV_UINT_DIV_186_93()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_186_62()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_186_31()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_186_6()   ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_186_3()   ~, (EPILEPSY_just(v(62)))
#define EPILEPSY_PRIV_UINT_DIV_186_2()   ~, (EPILEPSY_just(v(93)))
#define EPILEPSY_PRIV_UINT_DIV_186_186() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_187_1()   ~, (EPILEPSY_just(v(187)))
#define EPILEPSY_PRIV_UINT_DIV_187_17()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_187_11()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_187_187() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_188_1()   ~, (EPILEPSY_just(v(188)))
#define EPILEPSY_PRIV_UINT_DIV_188_94()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_188_47()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_188_4()   ~, (EPILEPSY_just(v(47)))
#define EPILEPSY_PRIV_UINT_DIV_188_2()   ~, (EPILEPSY_just(v(94)))
#define EPILEPSY_PRIV_UINT_DIV_188_188() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_189_1()   ~, (EPILEPSY_just(v(189)))
#define EPILEPSY_PRIV_UINT_DIV_189_63()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_189_27()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_189_21()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_189_9()   ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_189_7()   ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_189_3()   ~, (EPILEPSY_just(v(63)))
#define EPILEPSY_PRIV_UINT_DIV_189_189() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_190_1()   ~, (EPILEPSY_just(v(190)))
#define EPILEPSY_PRIV_UINT_DIV_190_95()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_190_38()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_190_19()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_190_10()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_190_5()   ~, (EPILEPSY_just(v(38)))
#define EPILEPSY_PRIV_UINT_DIV_190_2()   ~, (EPILEPSY_just(v(95)))
#define EPILEPSY_PRIV_UINT_DIV_190_190() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_191_1()   ~, (EPILEPSY_just(v(191)))
#define EPILEPSY_PRIV_UINT_DIV_191_191() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_192_1()   ~, (EPILEPSY_just(v(192)))
#define EPILEPSY_PRIV_UINT_DIV_192_96()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_192_64()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_192_48()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_192_32()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_192_24()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_192_16()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_192_12()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_192_8()   ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_192_6()   ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_192_4()   ~, (EPILEPSY_just(v(48)))
#define EPILEPSY_PRIV_UINT_DIV_192_3()   ~, (EPILEPSY_just(v(64)))
#define EPILEPSY_PRIV_UINT_DIV_192_2()   ~, (EPILEPSY_just(v(96)))
#define EPILEPSY_PRIV_UINT_DIV_192_192() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_193_1()   ~, (EPILEPSY_just(v(193)))
#define EPILEPSY_PRIV_UINT_DIV_193_193() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_194_1()   ~, (EPILEPSY_just(v(194)))
#define EPILEPSY_PRIV_UINT_DIV_194_97()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_194_2()   ~, (EPILEPSY_just(v(97)))
#define EPILEPSY_PRIV_UINT_DIV_194_194() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_195_1()   ~, (EPILEPSY_just(v(195)))
#define EPILEPSY_PRIV_UINT_DIV_195_65()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_195_39()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_195_15()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_195_13()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_195_5()   ~, (EPILEPSY_just(v(39)))
#define EPILEPSY_PRIV_UINT_DIV_195_3()   ~, (EPILEPSY_just(v(65)))
#define EPILEPSY_PRIV_UINT_DIV_195_195() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_196_1()   ~, (EPILEPSY_just(v(196)))
#define EPILEPSY_PRIV_UINT_DIV_196_98()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_196_49()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_196_28()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_196_14()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_196_7()   ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_196_4()   ~, (EPILEPSY_just(v(49)))
#define EPILEPSY_PRIV_UINT_DIV_196_2()   ~, (EPILEPSY_just(v(98)))
#define EPILEPSY_PRIV_UINT_DIV_196_196() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_197_1()   ~, (EPILEPSY_just(v(197)))
#define EPILEPSY_PRIV_UINT_DIV_197_197() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_198_1()   ~, (EPILEPSY_just(v(198)))
#define EPILEPSY_PRIV_UINT_DIV_198_99()  ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_198_66()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_198_33()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_198_22()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_198_18()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_198_11()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_198_9()   ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_198_6()   ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_198_3()   ~, (EPILEPSY_just(v(66)))
#define EPILEPSY_PRIV_UINT_DIV_198_2()   ~, (EPILEPSY_just(v(99)))
#define EPILEPSY_PRIV_UINT_DIV_198_198() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_199_1()   ~, (EPILEPSY_just(v(199)))
#define EPILEPSY_PRIV_UINT_DIV_199_199() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_200_1()   ~, (EPILEPSY_just(v(200)))
#define EPILEPSY_PRIV_UINT_DIV_200_100() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_200_50()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_200_40()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_200_25()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_200_20()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_200_10()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_200_8()   ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_200_5()   ~, (EPILEPSY_just(v(40)))
#define EPILEPSY_PRIV_UINT_DIV_200_4()   ~, (EPILEPSY_just(v(50)))
#define EPILEPSY_PRIV_UINT_DIV_200_2()   ~, (EPILEPSY_just(v(100)))
#define EPILEPSY_PRIV_UINT_DIV_200_200() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_201_1()   ~, (EPILEPSY_just(v(201)))
#define EPILEPSY_PRIV_UINT_DIV_201_67()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_201_3()   ~, (EPILEPSY_just(v(67)))
#define EPILEPSY_PRIV_UINT_DIV_201_201() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_202_1()   ~, (EPILEPSY_just(v(202)))
#define EPILEPSY_PRIV_UINT_DIV_202_101() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_202_2()   ~, (EPILEPSY_just(v(101)))
#define EPILEPSY_PRIV_UINT_DIV_202_202() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_203_1()   ~, (EPILEPSY_just(v(203)))
#define EPILEPSY_PRIV_UINT_DIV_203_29()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_203_7()   ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_203_203() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_204_1()   ~, (EPILEPSY_just(v(204)))
#define EPILEPSY_PRIV_UINT_DIV_204_102() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_204_68()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_204_51()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_204_34()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_204_17()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_204_12()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_204_6()   ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_204_4()   ~, (EPILEPSY_just(v(51)))
#define EPILEPSY_PRIV_UINT_DIV_204_3()   ~, (EPILEPSY_just(v(68)))
#define EPILEPSY_PRIV_UINT_DIV_204_2()   ~, (EPILEPSY_just(v(102)))
#define EPILEPSY_PRIV_UINT_DIV_204_204() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_205_1()   ~, (EPILEPSY_just(v(205)))
#define EPILEPSY_PRIV_UINT_DIV_205_41()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_205_5()   ~, (EPILEPSY_just(v(41)))
#define EPILEPSY_PRIV_UINT_DIV_205_205() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_206_1()   ~, (EPILEPSY_just(v(206)))
#define EPILEPSY_PRIV_UINT_DIV_206_103() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_206_2()   ~, (EPILEPSY_just(v(103)))
#define EPILEPSY_PRIV_UINT_DIV_206_206() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_207_1()   ~, (EPILEPSY_just(v(207)))
#define EPILEPSY_PRIV_UINT_DIV_207_69()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_207_23()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_207_9()   ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_207_3()   ~, (EPILEPSY_just(v(69)))
#define EPILEPSY_PRIV_UINT_DIV_207_207() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_208_1()   ~, (EPILEPSY_just(v(208)))
#define EPILEPSY_PRIV_UINT_DIV_208_104() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_208_52()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_208_26()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_208_16()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_208_13()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_208_8()   ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_208_4()   ~, (EPILEPSY_just(v(52)))
#define EPILEPSY_PRIV_UINT_DIV_208_2()   ~, (EPILEPSY_just(v(104)))
#define EPILEPSY_PRIV_UINT_DIV_208_208() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_209_1()   ~, (EPILEPSY_just(v(209)))
#define EPILEPSY_PRIV_UINT_DIV_209_19()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_209_11()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_209_209() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_210_1()   ~, (EPILEPSY_just(v(210)))
#define EPILEPSY_PRIV_UINT_DIV_210_105() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_210_70()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_210_42()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_210_35()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_210_30()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_210_21()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_210_15()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_210_14()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_210_10()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_210_7()   ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_210_6()   ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_210_5()   ~, (EPILEPSY_just(v(42)))
#define EPILEPSY_PRIV_UINT_DIV_210_3()   ~, (EPILEPSY_just(v(70)))
#define EPILEPSY_PRIV_UINT_DIV_210_2()   ~, (EPILEPSY_just(v(105)))
#define EPILEPSY_PRIV_UINT_DIV_210_210() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_211_1()   ~, (EPILEPSY_just(v(211)))
#define EPILEPSY_PRIV_UINT_DIV_211_211() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_212_1()   ~, (EPILEPSY_just(v(212)))
#define EPILEPSY_PRIV_UINT_DIV_212_106() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_212_53()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_212_4()   ~, (EPILEPSY_just(v(53)))
#define EPILEPSY_PRIV_UINT_DIV_212_2()   ~, (EPILEPSY_just(v(106)))
#define EPILEPSY_PRIV_UINT_DIV_212_212() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_213_1()   ~, (EPILEPSY_just(v(213)))
#define EPILEPSY_PRIV_UINT_DIV_213_71()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_213_3()   ~, (EPILEPSY_just(v(71)))
#define EPILEPSY_PRIV_UINT_DIV_213_213() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_214_1()   ~, (EPILEPSY_just(v(214)))
#define EPILEPSY_PRIV_UINT_DIV_214_107() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_214_2()   ~, (EPILEPSY_just(v(107)))
#define EPILEPSY_PRIV_UINT_DIV_214_214() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_215_1()   ~, (EPILEPSY_just(v(215)))
#define EPILEPSY_PRIV_UINT_DIV_215_43()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_215_5()   ~, (EPILEPSY_just(v(43)))
#define EPILEPSY_PRIV_UINT_DIV_215_215() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_216_1()   ~, (EPILEPSY_just(v(216)))
#define EPILEPSY_PRIV_UINT_DIV_216_108() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_216_72()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_216_54()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_216_36()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_216_27()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_216_24()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_216_18()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_216_12()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_216_9()   ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_216_8()   ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_216_6()   ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_216_4()   ~, (EPILEPSY_just(v(54)))
#define EPILEPSY_PRIV_UINT_DIV_216_3()   ~, (EPILEPSY_just(v(72)))
#define EPILEPSY_PRIV_UINT_DIV_216_2()   ~, (EPILEPSY_just(v(108)))
#define EPILEPSY_PRIV_UINT_DIV_216_216() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_217_1()   ~, (EPILEPSY_just(v(217)))
#define EPILEPSY_PRIV_UINT_DIV_217_31()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_217_7()   ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_217_217() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_218_1()   ~, (EPILEPSY_just(v(218)))
#define EPILEPSY_PRIV_UINT_DIV_218_109() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_218_2()   ~, (EPILEPSY_just(v(109)))
#define EPILEPSY_PRIV_UINT_DIV_218_218() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_219_1()   ~, (EPILEPSY_just(v(219)))
#define EPILEPSY_PRIV_UINT_DIV_219_73()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_219_3()   ~, (EPILEPSY_just(v(73)))
#define EPILEPSY_PRIV_UINT_DIV_219_219() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_220_1()   ~, (EPILEPSY_just(v(220)))
#define EPILEPSY_PRIV_UINT_DIV_220_110() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_220_55()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_220_44()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_220_22()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_220_20()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_220_11()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_220_10()  ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_220_5()   ~, (EPILEPSY_just(v(44)))
#define EPILEPSY_PRIV_UINT_DIV_220_4()   ~, (EPILEPSY_just(v(55)))
#define EPILEPSY_PRIV_UINT_DIV_220_2()   ~, (EPILEPSY_just(v(110)))
#define EPILEPSY_PRIV_UINT_DIV_220_220() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_221_1()   ~, (EPILEPSY_just(v(221)))
#define EPILEPSY_PRIV_UINT_DIV_221_17()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_221_13()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_221_221() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_222_1()   ~, (EPILEPSY_just(v(222)))
#define EPILEPSY_PRIV_UINT_DIV_222_111() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_222_74()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_222_37()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_222_6()   ~, (EPILEPSY_just(v(37)))
#define EPILEPSY_PRIV_UINT_DIV_222_3()   ~, (EPILEPSY_just(v(74)))
#define EPILEPSY_PRIV_UINT_DIV_222_2()   ~, (EPILEPSY_just(v(111)))
#define EPILEPSY_PRIV_UINT_DIV_222_222() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_223_1()   ~, (EPILEPSY_just(v(223)))
#define EPILEPSY_PRIV_UINT_DIV_223_223() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_224_1()   ~, (EPILEPSY_just(v(224)))
#define EPILEPSY_PRIV_UINT_DIV_224_112() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_224_56()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_224_32()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_224_28()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_224_16()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_224_14()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_224_8()   ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_224_7()   ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_224_4()   ~, (EPILEPSY_just(v(56)))
#define EPILEPSY_PRIV_UINT_DIV_224_2()   ~, (EPILEPSY_just(v(112)))
#define EPILEPSY_PRIV_UINT_DIV_224_224() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_225_1()   ~, (EPILEPSY_just(v(225)))
#define EPILEPSY_PRIV_UINT_DIV_225_75()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_225_45()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_225_25()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_225_15()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_225_9()   ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_225_5()   ~, (EPILEPSY_just(v(45)))
#define EPILEPSY_PRIV_UINT_DIV_225_3()   ~, (EPILEPSY_just(v(75)))
#define EPILEPSY_PRIV_UINT_DIV_225_225() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_226_1()   ~, (EPILEPSY_just(v(226)))
#define EPILEPSY_PRIV_UINT_DIV_226_113() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_226_2()   ~, (EPILEPSY_just(v(113)))
#define EPILEPSY_PRIV_UINT_DIV_226_226() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_227_1()   ~, (EPILEPSY_just(v(227)))
#define EPILEPSY_PRIV_UINT_DIV_227_227() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_228_1()   ~, (EPILEPSY_just(v(228)))
#define EPILEPSY_PRIV_UINT_DIV_228_114() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_228_76()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_228_57()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_228_38()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_228_19()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_228_12()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_228_6()   ~, (EPILEPSY_just(v(38)))
#define EPILEPSY_PRIV_UINT_DIV_228_4()   ~, (EPILEPSY_just(v(57)))
#define EPILEPSY_PRIV_UINT_DIV_228_3()   ~, (EPILEPSY_just(v(76)))
#define EPILEPSY_PRIV_UINT_DIV_228_2()   ~, (EPILEPSY_just(v(114)))
#define EPILEPSY_PRIV_UINT_DIV_228_228() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_229_1()   ~, (EPILEPSY_just(v(229)))
#define EPILEPSY_PRIV_UINT_DIV_229_229() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_230_1()   ~, (EPILEPSY_just(v(230)))
#define EPILEPSY_PRIV_UINT_DIV_230_115() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_230_46()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_230_23()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_230_10()  ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_230_5()   ~, (EPILEPSY_just(v(46)))
#define EPILEPSY_PRIV_UINT_DIV_230_2()   ~, (EPILEPSY_just(v(115)))
#define EPILEPSY_PRIV_UINT_DIV_230_230() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_231_1()   ~, (EPILEPSY_just(v(231)))
#define EPILEPSY_PRIV_UINT_DIV_231_77()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_231_33()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_231_21()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_231_11()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_231_7()   ~, (EPILEPSY_just(v(33)))
#define EPILEPSY_PRIV_UINT_DIV_231_3()   ~, (EPILEPSY_just(v(77)))
#define EPILEPSY_PRIV_UINT_DIV_231_231() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_232_1()   ~, (EPILEPSY_just(v(232)))
#define EPILEPSY_PRIV_UINT_DIV_232_116() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_232_58()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_232_29()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_232_8()   ~, (EPILEPSY_just(v(29)))
#define EPILEPSY_PRIV_UINT_DIV_232_4()   ~, (EPILEPSY_just(v(58)))
#define EPILEPSY_PRIV_UINT_DIV_232_2()   ~, (EPILEPSY_just(v(116)))
#define EPILEPSY_PRIV_UINT_DIV_232_232() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_233_1()   ~, (EPILEPSY_just(v(233)))
#define EPILEPSY_PRIV_UINT_DIV_233_233() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_234_1()   ~, (EPILEPSY_just(v(234)))
#define EPILEPSY_PRIV_UINT_DIV_234_117() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_234_78()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_234_39()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_234_26()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_234_18()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_234_13()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_234_9()   ~, (EPILEPSY_just(v(26)))
#define EPILEPSY_PRIV_UINT_DIV_234_6()   ~, (EPILEPSY_just(v(39)))
#define EPILEPSY_PRIV_UINT_DIV_234_3()   ~, (EPILEPSY_just(v(78)))
#define EPILEPSY_PRIV_UINT_DIV_234_2()   ~, (EPILEPSY_just(v(117)))
#define EPILEPSY_PRIV_UINT_DIV_234_234() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_235_1()   ~, (EPILEPSY_just(v(235)))
#define EPILEPSY_PRIV_UINT_DIV_235_47()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_235_5()   ~, (EPILEPSY_just(v(47)))
#define EPILEPSY_PRIV_UINT_DIV_235_235() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_236_1()   ~, (EPILEPSY_just(v(236)))
#define EPILEPSY_PRIV_UINT_DIV_236_118() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_236_59()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_236_4()   ~, (EPILEPSY_just(v(59)))
#define EPILEPSY_PRIV_UINT_DIV_236_2()   ~, (EPILEPSY_just(v(118)))
#define EPILEPSY_PRIV_UINT_DIV_236_236() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_237_1()   ~, (EPILEPSY_just(v(237)))
#define EPILEPSY_PRIV_UINT_DIV_237_79()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_237_3()   ~, (EPILEPSY_just(v(79)))
#define EPILEPSY_PRIV_UINT_DIV_237_237() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_238_1()   ~, (EPILEPSY_just(v(238)))
#define EPILEPSY_PRIV_UINT_DIV_238_119() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_238_34()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_238_17()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_238_14()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_238_7()   ~, (EPILEPSY_just(v(34)))
#define EPILEPSY_PRIV_UINT_DIV_238_2()   ~, (EPILEPSY_just(v(119)))
#define EPILEPSY_PRIV_UINT_DIV_238_238() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_239_1()   ~, (EPILEPSY_just(v(239)))
#define EPILEPSY_PRIV_UINT_DIV_239_239() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_240_1()   ~, (EPILEPSY_just(v(240)))
#define EPILEPSY_PRIV_UINT_DIV_240_120() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_240_80()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_240_60()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_240_48()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_240_40()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_240_30()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_240_24()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_240_20()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_240_16()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_240_15()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_240_12()  ~, (EPILEPSY_just(v(20)))
#define EPILEPSY_PRIV_UINT_DIV_240_10()  ~, (EPILEPSY_just(v(24)))
#define EPILEPSY_PRIV_UINT_DIV_240_8()   ~, (EPILEPSY_just(v(30)))
#define EPILEPSY_PRIV_UINT_DIV_240_6()   ~, (EPILEPSY_just(v(40)))
#define EPILEPSY_PRIV_UINT_DIV_240_5()   ~, (EPILEPSY_just(v(48)))
#define EPILEPSY_PRIV_UINT_DIV_240_4()   ~, (EPILEPSY_just(v(60)))
#define EPILEPSY_PRIV_UINT_DIV_240_3()   ~, (EPILEPSY_just(v(80)))
#define EPILEPSY_PRIV_UINT_DIV_240_2()   ~, (EPILEPSY_just(v(120)))
#define EPILEPSY_PRIV_UINT_DIV_240_240() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_241_1()   ~, (EPILEPSY_just(v(241)))
#define EPILEPSY_PRIV_UINT_DIV_241_241() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_242_1()   ~, (EPILEPSY_just(v(242)))
#define EPILEPSY_PRIV_UINT_DIV_242_121() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_242_22()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_242_11()  ~, (EPILEPSY_just(v(22)))
#define EPILEPSY_PRIV_UINT_DIV_242_2()   ~, (EPILEPSY_just(v(121)))
#define EPILEPSY_PRIV_UINT_DIV_242_242() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_243_1()   ~, (EPILEPSY_just(v(243)))
#define EPILEPSY_PRIV_UINT_DIV_243_81()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_243_27()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_243_9()   ~, (EPILEPSY_just(v(27)))
#define EPILEPSY_PRIV_UINT_DIV_243_3()   ~, (EPILEPSY_just(v(81)))
#define EPILEPSY_PRIV_UINT_DIV_243_243() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_244_1()   ~, (EPILEPSY_just(v(244)))
#define EPILEPSY_PRIV_UINT_DIV_244_122() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_244_61()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_244_4()   ~, (EPILEPSY_just(v(61)))
#define EPILEPSY_PRIV_UINT_DIV_244_2()   ~, (EPILEPSY_just(v(122)))
#define EPILEPSY_PRIV_UINT_DIV_244_244() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_245_1()   ~, (EPILEPSY_just(v(245)))
#define EPILEPSY_PRIV_UINT_DIV_245_49()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_245_35()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_245_7()   ~, (EPILEPSY_just(v(35)))
#define EPILEPSY_PRIV_UINT_DIV_245_5()   ~, (EPILEPSY_just(v(49)))
#define EPILEPSY_PRIV_UINT_DIV_245_245() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_246_1()   ~, (EPILEPSY_just(v(246)))
#define EPILEPSY_PRIV_UINT_DIV_246_123() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_246_82()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_246_41()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_246_6()   ~, (EPILEPSY_just(v(41)))
#define EPILEPSY_PRIV_UINT_DIV_246_3()   ~, (EPILEPSY_just(v(82)))
#define EPILEPSY_PRIV_UINT_DIV_246_2()   ~, (EPILEPSY_just(v(123)))
#define EPILEPSY_PRIV_UINT_DIV_246_246() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_247_1()   ~, (EPILEPSY_just(v(247)))
#define EPILEPSY_PRIV_UINT_DIV_247_19()  ~, (EPILEPSY_just(v(13)))
#define EPILEPSY_PRIV_UINT_DIV_247_13()  ~, (EPILEPSY_just(v(19)))
#define EPILEPSY_PRIV_UINT_DIV_247_247() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_248_1()   ~, (EPILEPSY_just(v(248)))
#define EPILEPSY_PRIV_UINT_DIV_248_124() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_248_62()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_248_31()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_248_8()   ~, (EPILEPSY_just(v(31)))
#define EPILEPSY_PRIV_UINT_DIV_248_4()   ~, (EPILEPSY_just(v(62)))
#define EPILEPSY_PRIV_UINT_DIV_248_2()   ~, (EPILEPSY_just(v(124)))
#define EPILEPSY_PRIV_UINT_DIV_248_248() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_249_1()   ~, (EPILEPSY_just(v(249)))
#define EPILEPSY_PRIV_UINT_DIV_249_83()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_249_3()   ~, (EPILEPSY_just(v(83)))
#define EPILEPSY_PRIV_UINT_DIV_249_249() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_250_1()   ~, (EPILEPSY_just(v(250)))
#define EPILEPSY_PRIV_UINT_DIV_250_125() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_250_50()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_250_25()  ~, (EPILEPSY_just(v(10)))
#define EPILEPSY_PRIV_UINT_DIV_250_10()  ~, (EPILEPSY_just(v(25)))
#define EPILEPSY_PRIV_UINT_DIV_250_5()   ~, (EPILEPSY_just(v(50)))
#define EPILEPSY_PRIV_UINT_DIV_250_2()   ~, (EPILEPSY_just(v(125)))
#define EPILEPSY_PRIV_UINT_DIV_250_250() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_251_1()   ~, (EPILEPSY_just(v(251)))
#define EPILEPSY_PRIV_UINT_DIV_251_251() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_252_1()   ~, (EPILEPSY_just(v(252)))
#define EPILEPSY_PRIV_UINT_DIV_252_126() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_252_84()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_252_63()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_252_42()  ~, (EPILEPSY_just(v(6)))
#define EPILEPSY_PRIV_UINT_DIV_252_36()  ~, (EPILEPSY_just(v(7)))
#define EPILEPSY_PRIV_UINT_DIV_252_28()  ~, (EPILEPSY_just(v(9)))
#define EPILEPSY_PRIV_UINT_DIV_252_21()  ~, (EPILEPSY_just(v(12)))
#define EPILEPSY_PRIV_UINT_DIV_252_18()  ~, (EPILEPSY_just(v(14)))
#define EPILEPSY_PRIV_UINT_DIV_252_14()  ~, (EPILEPSY_just(v(18)))
#define EPILEPSY_PRIV_UINT_DIV_252_12()  ~, (EPILEPSY_just(v(21)))
#define EPILEPSY_PRIV_UINT_DIV_252_9()   ~, (EPILEPSY_just(v(28)))
#define EPILEPSY_PRIV_UINT_DIV_252_7()   ~, (EPILEPSY_just(v(36)))
#define EPILEPSY_PRIV_UINT_DIV_252_6()   ~, (EPILEPSY_just(v(42)))
#define EPILEPSY_PRIV_UINT_DIV_252_4()   ~, (EPILEPSY_just(v(63)))
#define EPILEPSY_PRIV_UINT_DIV_252_3()   ~, (EPILEPSY_just(v(84)))
#define EPILEPSY_PRIV_UINT_DIV_252_2()   ~, (EPILEPSY_just(v(126)))
#define EPILEPSY_PRIV_UINT_DIV_252_252() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_253_1()   ~, (EPILEPSY_just(v(253)))
#define EPILEPSY_PRIV_UINT_DIV_253_23()  ~, (EPILEPSY_just(v(11)))
#define EPILEPSY_PRIV_UINT_DIV_253_11()  ~, (EPILEPSY_just(v(23)))
#define EPILEPSY_PRIV_UINT_DIV_253_253() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_254_1()   ~, (EPILEPSY_just(v(254)))
#define EPILEPSY_PRIV_UINT_DIV_254_127() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_254_2()   ~, (EPILEPSY_just(v(127)))
#define EPILEPSY_PRIV_UINT_DIV_254_254() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_255_1()   ~, (EPILEPSY_just(v(255)))
#define EPILEPSY_PRIV_UINT_DIV_255_85()  ~, (EPILEPSY_just(v(3)))
#define EPILEPSY_PRIV_UINT_DIV_255_51()  ~, (EPILEPSY_just(v(5)))
#define EPILEPSY_PRIV_UINT_DIV_255_17()  ~, (EPILEPSY_just(v(15)))
#define EPILEPSY_PRIV_UINT_DIV_255_15()  ~, (EPILEPSY_just(v(17)))
#define EPILEPSY_PRIV_UINT_DIV_255_5()   ~, (EPILEPSY_just(v(51)))
#define EPILEPSY_PRIV_UINT_DIV_255_3()   ~, (EPILEPSY_just(v(85)))
#define EPILEPSY_PRIV_UINT_DIV_255_255() ~, (EPILEPSY_just(v(1)))

#define EPILEPSY_PRIV_UINT_DIV_256_1()   ~, (EPILEPSY_just(v(256)))
#define EPILEPSY_PRIV_UINT_DIV_256_128() ~, (EPILEPSY_just(v(2)))
#define EPILEPSY_PRIV_UINT_DIV_256_64()  ~, (EPILEPSY_just(v(4)))
#define EPILEPSY_PRIV_UINT_DIV_256_32()  ~, (EPILEPSY_just(v(8)))
#define EPILEPSY_PRIV_UINT_DIV_256_16()  ~, (EPILEPSY_just(v(16)))
#define EPILEPSY_PRIV_UINT_DIV_256_8()   ~, (EPILEPSY_just(v(32)))
#define EPILEPSY_PRIV_UINT_DIV_256_4()   ~, (EPILEPSY_just(v(64)))
#define EPILEPSY_PRIV_UINT_DIV_256_2()   ~, (EPILEPSY_just(v(128)))
#define EPILEPSY_PRIV_UINT_DIV_256_256() ~, (EPILEPSY_just(v(1)))

#endif // EPILEPSY_UINT_DIV_H
