#ifndef MACROLOP_VARIADICS_GET_H
#define MACROLOP_VARIADICS_GET_H

#include "../lang.h"

#define MACROLOP_VARIADICS_HEAD_REAL(x, ...) v(x)
#define MACROLOP_VARIADICS_TAIL_REAL(x, ...) v(__VA_ARGS__)

#endif // MACROLOP_VARIADICS_GET_H
