#ifndef ML99_PRIV_COMPILER_SPECIFIC_H
#define ML99_PRIV_COMPILER_SPECIFIC_H

#ifdef __GNUC__
#define ML99_PRIV_COMPILER_ATTR_UNUSED __attribute__((unused))
#else
#define ML99_PRIV_COMPILER_ATTR_UNUSED
#endif

#endif // ML99_PRIV_COMPILER_SPECIFIC_H
