#ifndef EPILEPSY_PRIV_AUX_H
#define EPILEPSY_PRIV_AUX_H

#include <epilepsy/priv/variadics/get.h>

#define EPILEPSY_PRIV_CAT(x, y)           EPILEPSY_PRIV_PRIMITIVE_CAT(x, y)
#define EPILEPSY_PRIV_PRIMITIVE_CAT(x, y) x##y

#define EPILEPSY_PRIV_EXPAND(...)    __VA_ARGS__
#define EPILEPSY_PRIV_INVOKE(f, ...) f(__VA_ARGS__)

#define EPILEPSY_PRIV_PARENTHESISE(...) (__VA_ARGS__)
#define EPILEPSY_PRIV_UNPARENTHESISE(x) EPILEPSY_PRIV_EXPAND(EPILEPSY_PRIV_EXPAND x)

#define EPILEPSY_PRIV_IF(cond, x, y) EPILEPSY_PRIV_CAT(EPILEPSY_PRIV_IF_, cond)((x), (y))
#define EPILEPSY_PRIV_IF_0(_x, y)    EPILEPSY_PRIV_UNPARENTHESISE(y)
#define EPILEPSY_PRIV_IF_1(x, _y)    EPILEPSY_PRIV_UNPARENTHESISE(x)

#define EPILEPSY_PRIV_IS_UNPARENTHESISED(x)                                                        \
    EPILEPSY_PRIV_VARIADICS_SND(EPILEPSY_PRIV_IS_UNPARENTHESISED_TEST x, 1, ~)
#define EPILEPSY_PRIV_IS_UNPARENTHESISED_TEST(...) ~, 0

#define EPILEPSY_PRIV_IS_PARENTHESISED(x)                                                          \
    EPILEPSY_PRIV_VARIADICS_SND(EPILEPSY_PRIV_IS_PARENTHESISED_TEST x, 0, ~)
#define EPILEPSY_PRIV_IS_PARENTHESISED_TEST(...) ~, 1

#endif // EPILEPSY_PRIV_AUX_H
