#ifndef EPILEPSY_PRIV_AUX_H
#define EPILEPSY_PRIV_AUX_H

#include <epilepsy/priv/variadics/get.h>

#define EPILEPSY_PRIV_CAT(x, y)           EPILEPSY_PRIV_PRIMITIVE_CAT(x, y)
#define EPILEPSY_PRIV_PRIMITIVE_CAT(x, y) x##y

#define EPILEPSY_PRIV_CAT_3(x, y, z)    EPILEPSY_PRIV_CAT(x, EPILEPSY_PRIV_CAT(y, z))
#define EPILEPSY_PRIV_CAT_4(x, y, z, a) EPILEPSY_PRIV_CAT_3(x, y, EPILEPSY_PRIV_CAT(z, a))

#define EPILEPSY_PRIV_MATCH(op, pattern) EPILEPSY_PRIV_CAT(op, pattern)

#define EPILEPSY_PRIV_EMPTY()
#define EPILEPSY_PRIV_EXPAND(...)    __VA_ARGS__
#define EPILEPSY_PRIV_CONSUME(...)   EPILEPSY_PRIV_EMPTY()
#define EPILEPSY_PRIV_COMMA()        ,
#define EPILEPSY_PRIV_INVOKE(f, ...) f(__VA_ARGS__)

#define EPILEPSY_PRIV_PARENTHESISE(...) (__VA_ARGS__)
#define EPILEPSY_PRIV_UNPARENTHESISE(x) EPILEPSY_PRIV_EXPAND(EPILEPSY_PRIV_EXPAND x)

#define EPILEPSY_PRIV_IF(cond, x, y) EPILEPSY_PRIV_MATCH(EPILEPSY_PRIV_IF_, cond)((x), (y))
#define EPILEPSY_PRIV_IF_0(_x, y)    EPILEPSY_PRIV_UNPARENTHESISE(y)
#define EPILEPSY_PRIV_IF_1(x, _y)    EPILEPSY_PRIV_UNPARENTHESISE(x)

#define EPILEPSY_PRIV_IS_UNPARENTHESISED(x)                                                        \
    EPILEPSY_PRIV_VARIADICS_SND(EPILEPSY_PRIV_IS_UNPARENTHESISED_TEST x, 1, ~)
#define EPILEPSY_PRIV_IS_UNPARENTHESISED_TEST(...) ~, 0

#endif // EPILEPSY_PRIV_AUX_H
