#ifndef EPILEPSY_PRIV_COMPILER_ATTR_H
#define EPILEPSY_PRIV_COMPILER_ATTR_H

#ifdef __GNUC__
#define EPILEPSY_PRIV_COMPILER_ATTR_UNUSED __attribute__((unused))
#else
#define EPILEPSY_PRIV_COMPILER_ATTR_UNUSED
#endif

#endif // EPILEPSY_PRIV_COMPILER_ATTR_H
