#ifndef EPILEPSY_PRIV_LOGICAL_H
#define EPILEPSY_PRIV_LOGICAL_H

#include <epilepsy/priv/aux.h>

#define EPILEPSY_PRIV_NOT(x)  EPILEPSY_PRIV_CAT(EPILEPSY_PRIV_NOT_, x)()
#define EPILEPSY_PRIV_NOT_0() 1
#define EPILEPSY_PRIV_NOT_1() 0

#define EPILEPSY_PRIV_AND(x, y) EPILEPSY_PRIV_CAT_3(EPILEPSY_PRIV_AND_, x, y)()
#define EPILEPSY_PRIV_AND_00()  0
#define EPILEPSY_PRIV_AND_01()  0
#define EPILEPSY_PRIV_AND_10()  0
#define EPILEPSY_PRIV_AND_11()  1

#define EPILEPSY_PRIV_OR(x, y) EPILEPSY_PRIV_CAT_3(EPILEPSY_PRIV_OR_, x, y)()
#define EPILEPSY_PRIV_OR_00()  0
#define EPILEPSY_PRIV_OR_01()  1
#define EPILEPSY_PRIV_OR_10()  1
#define EPILEPSY_PRIV_OR_11()  1

#define EPILEPSY_PRIV_XOR(x, y) EPILEPSY_PRIV_CAT_3(EPILEPSY_PRIV_XOR_, x, y)()
#define EPILEPSY_PRIV_XOR_00()  0
#define EPILEPSY_PRIV_XOR_01()  1
#define EPILEPSY_PRIV_XOR_10()  1
#define EPILEPSY_PRIV_XOR_11()  0

#endif // EPILEPSY_PRIV_LOGICAL_H
