#ifndef KOSHMAR_PP_PRIVATE_AUX_H
#define KOSHMAR_PP_PRIVATE_AUX_H

#define KOSHMAR_PP_PRIVATE_EMPTY()
#define KOSHMAR_PP_PRIVATE_EXPAND(...)         __VA_ARGS__
#define KOSHMAR_PP_PRIVATE_COMMA()             ,
#define KOSHMAR_PP_PRIVATE_CALL_MACRO(op, ...) op(__VA_ARGS__)

#define KOSHMAR_PP_PRIVATE_PARENTHESISE(...) (__VA_ARGS__)
#define KOSHMAR_PP_PRIVATE_UNPARENTHESISE(x) KOSHMAR_PP_PRIVATE_EXPAND(KOSHMAR_PP_PRIVATE_EXPAND x)

#define KOSHMAR_PP_PRIVATE_CAT(x, y)           KOSHMAR_PP_PRIVATE_PRIMITIVE_CAT(x, y)
#define KOSHMAR_PP_PRIVATE_PRIMITIVE_CAT(x, y) x##y

#define KOSHMAR_PP_PRIVATE_MATCH(op, pattern) KOSHMAR_PP_PRIVATE_CAT(op, pattern)

#define KOSHMAR_PP_PRIVATE_HEAD(...)        KOSHMAR_PP_PRIVATE_HEAD_AUX(__VA_ARGS__)
#define KOSHMAR_PP_PRIVATE_HEAD_AUX(x, ...) x

#define KOSHMAR_PP_PRIVATE_TAIL(...)        KOSHMAR_PP_PRIVATE_TAIL_AUX(__VA_ARGS__)
#define KOSHMAR_PP_PRIVATE_TAIL_AUX(x, ...) __VA_ARGS__

#define KOSHMAR_PP_PRIVATE_IF(cond, x, y)                                                          \
    KOSHMAR_PP_PRIVATE_MATCH(KOSHMAR_PP_PRIVATE_IF_, cond)((x), (y))
#define KOSHMAR_PP_PRIVATE_IF_0(_x, y) KOSHMAR_PP_PRIVATE_UNPARENTHESISE(y)
#define KOSHMAR_PP_PRIVATE_IF_1(x, _y) KOSHMAR_PP_PRIVATE_UNPARENTHESISE(x)

#endif // KOSHMAR_PP_PRIVATE_AUX_H
