#ifndef AGONY_PP_VARIADICS_GET_H
#define AGONY_PP_VARIADICS_GET_H

#define AGONY_PP_PRIVATE_VARIADICS_HEAD(x, ...) x
#define AGONY_PP_PRIVATE_VARIADICS_TAIL(x, ...) __VA_ARGS__

#endif // AGONY_PP_VARIADICS_GET_H
