#ifndef MACROLOP_PRIV_AUX_H
#define MACROLOP_PRIV_AUX_H

#define MACROLOP_PRIV_AUX_CAT(x, y)           MACROLOP_PRIV_AUX_PRIMITIVE_CAT(x, y)
#define MACROLOP_PRIV_AUX_PRIMITIVE_CAT(x, y) x##y

#define MACROLOP_PRIV_AUX_CAT_3(x, y, z) MACROLOP_PRIV_AUX_CAT(x, MACROLOP_PRIV_AUX_CAT(y, z))

#define MACROLOP_PRIV_AUX_MATCH(op, pattern) MACROLOP_PRIV_AUX_CAT(op, pattern)

#define MACROLOP_PRIV_AUX_EMPTY()
#define MACROLOP_PRIV_AUX_EXPAND(...)  __VA_ARGS__
#define MACROLOP_PRIV_AUX_CONSUME(...) MACROLOP_PRIV_AUX_EMPTY()
#define MACROLOP_PRIV_AUX_COMMA()      ,

#define MACROLOP_PRIV_AUX_PARENTHESISE(...) (__VA_ARGS__)
#define MACROLOP_PRIV_AUX_UNPARENTHESISE(x) MACROLOP_PRIV_AUX_EXPAND(MACROLOP_PRIV_AUX_EXPAND x)

#define MACROLOP_PRIV_AUX_IF(cond, x, y)                                                           \
    MACROLOP_PRIV_AUX_MATCH(MACROLOP_PRIV_AUX_IF_, cond)((x), (y))
#define MACROLOP_PRIV_AUX_IF_0(_x, y) MACROLOP_PRIV_AUX_UNPARENTHESISE(y)
#define MACROLOP_PRIV_AUX_IF_1(x, _y) MACROLOP_PRIV_AUX_UNPARENTHESISE(x)

#endif // MACROLOP_PRIV_AUX_H
