#ifndef MACROLOP_PRIV_LOGICAL_H
#define MACROLOP_PRIV_LOGICAL_H

#include <macrolop/priv/aux.h>

#define MACROLOP_PRIV_NOT(x)  MACROLOP_PRIV_AUX_CAT(MACROLOP_PRIV_NOT_, x)()
#define MACROLOP_PRIV_NOT_0() 1
#define MACROLOP_PRIV_NOT_1() 0

#define MACROLOP_PRIV_AND(x, y) MACROLOP_PRIV_AUX_CAT_3(MACROLOP_PRIV_AND_, x, y)()
#define MACROLOP_PRIV_AND_00()  0
#define MACROLOP_PRIV_AND_01()  0
#define MACROLOP_PRIV_AND_10()  0
#define MACROLOP_PRIV_AND_11()  1

#define MACROLOP_PRIV_OR(x, y) MACROLOP_PRIV_AUX_CAT_3(MACROLOP_PRIV_OR_, x, y)()
#define MACROLOP_PRIV_OR_00()  0
#define MACROLOP_PRIV_OR_01()  1
#define MACROLOP_PRIV_OR_10()  1
#define MACROLOP_PRIV_OR_11()  1

#define MACROLOP_PRIV_XOR(x, y) MACROLOP_PRIV_AUX_CAT_3(MACROLOP_PRIV_XOR_, x, y)()
#define MACROLOP_PRIV_XOR_00()  0
#define MACROLOP_PRIV_XOR_01()  1
#define MACROLOP_PRIV_XOR_10()  1
#define MACROLOP_PRIV_XOR_11()  0

#endif // MACROLOP_PRIV_LOGICAL_H
