#ifndef MACROLOP_PRIV_VARIADICS_GET_H
#define MACROLOP_PRIV_VARIADICS_GET_H

#define MACROLOP_PRIV_VARIADICS_HEAD(...)        MACROLOP_PRIV_VARIADICS_HEAD_AUX(__VA_ARGS__)
#define MACROLOP_PRIV_VARIADICS_HEAD_AUX(x, ...) x

#define MACROLOP_PRIV_VARIADICS_TAIL(...)        MACROLOP_PRIV_VARIADICS_TAIL_AUX(__VA_ARGS__)
#define MACROLOP_PRIV_VARIADICS_TAIL_AUX(x, ...) __VA_ARGS__

#endif // MACROLOP_PRIV_VARIADICS_GET_H
