#ifndef KOSHMAR_PP_LIMITS_H
#define KOSHMAR_PP_LIMITS_H

#define KOSHMAR_PP_UINT_MAX  1023
#define KOSHMAR_PP_REC_LIMIT 1024
#define KOSHMAR_PP_FOR_LIMIT KOSHMAR_PP_REC_LIMIT

#endif // KOSHMAR_PP_LIMITS_H
