#ifndef KOSHMAR_PP_STRINGIFY_H
#define KOSHMAR_PP_STRINGIFY_H

#define KOSHMAR_PP_STRINGIFY(x)           KOSHMAR_PP_PRIMITIVE_STRINGIFY(x)
#define KOSHMAR_PP_PRIMITIVE_STRINGIFY(x) #x

#endif // KOSHMAR_PP_STRINGIFY_H
