#ifndef KOSHMAR_PP_VARIADICS_GET_H
#define KOSHMAR_PP_VARIADICS_GET_H

#define KOSHMAR_PP_VARIADICS_HEAD(x, ...) x
#define KOSHMAR_PP_VARIADICS_TAIL(x, ...) __VA_ARGS__

#endif // KOSHMAR_PP_VARIADICS_GET_H
