name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Tests
      run: |
        mkdir tests/build
        cd tests/build
        cmake ..
        cmake --build .

    - name: Examples
      run: |
        mkdir examples/build
        cd examples/build
        cmake ..
        cmake --build .

  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bench
        run: bash scripts/bench.sh

  check-arities:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check arity specifiers
        run: python3 scripts/check-arities.py

  check-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download run-clang-format
        run: git submodule update --init run-clang-format

      - name: Check code formatting
        run: bash scripts/check-fmt.sh
