name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            compiler: tcc

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Tests
      run: bash scripts/test-all.sh

  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bench
        run: bash scripts/bench.sh

  check-arities:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt install doxygen

      - name: Check arity specifiers
        run: python3 scripts/check-arities.py

  check-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download run-clang-format
        run: git submodule update --init run-clang-format

      - name: Check code formatting
        run: bash scripts/check-fmt.sh
