name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: Test
      run: ./scripts/test.sh

    - name: Check code formatting
      run: ./scripts/check-fmt.sh
